MissionProject/Models/Mission.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MissionProject.Models
{
    public class Mission
    {
        public int MissionId { get; set; }
        public string MissionName { get; set; }
        public string MissionDescription { get; set; }
        public DateTime AssignDate { get; set; }
        public int MutantId { get; set; }
        public int StatusId { get; set; }
        public virtual Mutant mutant { get; set; }
        public virtual Status status { get; set; }
    }
}

MissionProject/Controllers/MissionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MissionProject.Models;
using XaviersSchool.Models;

namespace MissionProject.Controllers
{
    public class MissionController : Controller
    {
        private MissionContext db = new MissionContext();

        public ActionResult Search(string SearchBox)
        {
            var missions = (from m in db.Missions
                            where
                               m.MissionName.Contains(SearchBox)
                               || m.MissionDescription.Contains(SearchBox)
                               || m.mutant.MutantName.Contains(SearchBox)
                               || m.status.StatusName.Contains(SearchBox)
                            select m).ToList();
            return View("Index", missions);
        }


        // GET: Mission
        public ActionResult Index()
        {
            var missions = db.Missions.Include(m => m.mutant).Include(m => m.status);
            return View(missions.ToList());
        }

        // GET: Mission/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mission mission = db.Missions.Find(id);
            if (mission == null)
            {
                return HttpNotFound();
            }
            return View(mission);
        }

        // GET: Mission/Create
        public ActionResult Create()
        {
            ViewBag.MutantId = new SelectList(db.Mutants, "MutantId", "MutantName");
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName");
            return View();
        }

        // POST: Mission/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MissionId,MissionName,MissionDescription,AssignDate,MutantId,StatusId")] Mission mission)
        {
            if (ModelState.IsValid)
            {
                db.Missions.Add(mission);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MutantId = new SelectList(db.Mutants, "MutantId", "MutantName", mission.MutantId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", mission.StatusId);
            return View(mission);
        }

        // GET: Mission/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mission mission = db.Missions.Find(id);
            if (mission == null)
            {
                return HttpNotFound();
            }
            ViewBag.MutantId = new SelectList(db.Mutants, "MutantId", "MutantName", mission.MutantId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", mission.StatusId);
            return View(mission);
        }

        // POST: Mission/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MissionId,MissionName,MissionDescription,AssignDate,MutantId,StatusId")] Mission mission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MutantId = new SelectList(db.Mutants, "MutantId", "MutantName", mission.MutantId);
            ViewBag.StatusId = new SelectList(db.Statuses, "StatusId", "StatusName", mission.StatusId);
            return View(mission);
        }

        // GET: Mission/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mission mission = db.Missions.Find(id);
            if (mission == null)
            {
                return HttpNotFound();
            }
            return View(mission);
        }

        // POST: Mission/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Mission mission = db.Missions.Find(id);
            db.Missions.Remove(mission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MissionProject/Views/Mission/Create.cshtml
@model MissionProject.Models.Mission

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mission</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MissionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MissionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MissionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MissionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MissionDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MissionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssignDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MutantId, "MutantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MutantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MutantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MissionProject/Views/Mission/Delete.cshtml
@model MissionProject.Models.Mission

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mutant.MutantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mutant.MutantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MissionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MissionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MissionDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MissionDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MissionProject/Views/Mission/Details.cshtml
@model MissionProject.Models.Mission

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Mission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mutant Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mutant.MutantName)
        </dd>

        <dt>
            Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status.StatusName)
        </dd>

        <dt>
            Mission Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MissionName)
        </dd>
        <dt>
            Assign Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignDate)
        </dd>

        @if (Model.mutant.ImagePath != null)
        {
            <dd>
                <img src="~/images/profile/@Model.mutant.ImagePath" width="200" height="200" />
            </dd>
        }





    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MissionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MissionProject/Views/Mission/Edit.cshtml
@model MissionProject.Models.Mission

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mission</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MissionId)

        <div class="form-group">
            @Html.LabelFor(model => model.MissionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MissionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MissionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MissionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MissionDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MissionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssignDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MutantId, "MutantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MutantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MutantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MissionProject/Views/Mission/Index.cshtml
@model IEnumerable<MissionProject.Models.Mission>

<h2>Missions</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Search", "Mission"))
{
    @Html.Editor("SearchBox")
    <input type="submit" value="Search" />
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.mutant.MutantName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status.StatusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MissionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignDate)
        </th>
        <th>
            Revise
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.mutant.MutantName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status.StatusName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MissionName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MissionId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MissionId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MissionId })
        </td>
    </tr>
}

</table>